<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$locationdetail = new LocationDetail();
	
	// default title is to enable adding any payee
	$title = $this->translate("locationdetail_pagetitle_view"); 
	
	$locationdetail->populate(decode($request->id));
	
	$this->headTitle($title);  
?>
<div class="pageinfo"><?php echo $this->translate("locationdetail_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
      <td class="label"><?php echo $this->translate("locationdetail_summary_label"); ?>:</td>
      <td class="nowrapping"><?php echo $locationdetail->getSummary(); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationdetail_agriculturalinputprices_label"); ?>:</td>
      <td class="nowrapping"><?php echo $locationdetail->getAgriculturalInputPrices(); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationdetail_businesssector_label"); ?>:</td>
      <td class="nowrapping"><?php echo $locationdetail->getBusinessSector(); ?></td>
    </tr> 
    <tr>
      <td class="label"><?php echo $this->translate("locationdetail_tourismsector_label"); ?>:</td>
      <td class="nowrapping"><?php echo $locationdetail->getTourismSector(); ?></td>
    </tr> 
    <tr>
      <td class="label"><?php echo $this->translate("locationdetail_cropproduction_label"); ?>:</td>
      <td class="nowrapping"><?php echo $locationdetail->getCropProduction(); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationdetail_livestockproduction_label"); ?>:</td>
      <td class="nowrapping"><?php echo $locationdetail->getLivestockProduction(); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationdetail_handcraftsector_label"); ?>:</td>
      <td class="nowrapping"><?php echo $locationdetail->getHandcraftSector(); ?></td>
    </tr>
    <tr>
    	<td class="label"><?php echo $this->translate("locationdetail_fishproduction_label"); ?>:</td>
    	<td class="nowrapping"><?php echo $locationdetail->getFishProduction(); ?></td>
    </tr>
</table>
<table class="formtable formactions">
  <tfoot>
    <?php if ($acl->checkPermission('Location Details', ACTION_EDIT)) { ?>
      <tr>
        <td align="center" colspan="3"><a href="<?php echo $this->baseUrl("locationdetail/index/id/".encode($locationdetail->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("locationdetail_button_update"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("locationdetail_button_update"); ?></a>
          </td>
          </tr>
<?php } ?>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
