<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$locationstatistic = new Locationstatistic(); 
	
	// default title is to enable adding any payee
	$title = $this->translate("locationstatistic_pagetitle_new"); 
	$posturl = $this->baseUrl("locationstatistic/create");
	$button_title = $this->translate("locationstatistic_button_new"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$locationstatistic->populate(decode($request->id));
		$title = sprintf($this->translate("locationstatistic_pagetitle_edit"), $locationstatistic->getLocationID()); 
		$button_title = $this->translate("locationstatistic_button_edit");
		$posturl = $this->baseUrl("locationstatistic/edit"); 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$locationstatistic->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		// configure the date picker not to accept dates before today
		// datepickerOpts.minDate = new Date();   
		 
		datepickerOpts.minDate = new Date();   
		$("#startdate, #enddate").datepicker(datepickerOpts);
		
		$("#locationstatisticform").validate({		
			// define the validation rules one field at a time
			rules: {
				locationid: "required",
				startdate: "required",
				enddate: {
					"required": true, 					
					enddateafterstartdate: true
				},
				statistic: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {				
				locationid: "<?php echo $this->translate("locationstatistic_location_error"); ?>",
				startdate: "<?php echo $this->translate("locationstatistic_startdate_error"); ?>",
				enddate: "<?php echo $this->translate("locationstatistic_enddate_error"); ?>",
				statistic: "<?php echo $this->translate("locationstatistic_statistic_error"); ?>"
			}
		});

	});
</script>

<div class="pageinfo"><?php echo $this->translate("locationstatistic_page_info"); ?></div>
<form id="locationstatisticform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
     
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_locationid_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
       <td><?php
      	$districtlist = new LookupType(); 
      	$districtlist->setName("ALL_DISTRICTS");
       	$districtdropdown = new Zend_Form_Element_Select('locationid',
							array(
								'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $districtlist->getOptionValuesFromQuery()),								
								'view' => new Zend_View(),
								'decorators' => array('ViewHelper'),
								'class' => array("filterselect", 'chzn-select'),
							)
						);
		$districtdropdown->setValue($locationstatistic->getLocationID()); 
		echo $districtdropdown->render(); 
      ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_startdate_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
     <td><input name="startdate" id="startdate" class="datefield startdate" type="text" value="<?php echo changemySQlDatetoPageFormat($locationstatistic->getStartDate()); ?>" /></td>
    </tr>
     <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_enddate_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
     <td><input name="enddate" id="enddate" class="datefield" type="text" value="<?php echo changemySQlDatetoPageFormat($locationstatistic->getEndDate()); ?>" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_statistic_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
       <td><?php 	
				# lookup for statistics
				$statistic = new LookupType();
				$statistic->setName("LGMIS_LOCATION_STATISTICS");
	
				$stat = new Zend_Form_Element_Select('statistic',
								array(
									'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $statistic->getOptionValuesAndDescription()),								
									'view' => new Zend_View(),
									'decorators' => array('ViewHelper')
								)
							);
				
				$stat->setValue($locationstatistic->getStatistic());				
				echo $stat->render();	
			?></td>
    </tr>
    		
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_value_label"); ?></td>
      <td><input type="text" name="value" id="value" value="<?php echo $locationstatistic->getValue(); ?>" /></td>
    </tr>	
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("dataentry"); ?>" title="Cancel">Cancel</a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction" id="submit" name="submit"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
          <input type="hidden" name="entityname" value="Locationstatistic" />
          <input type="hidden" id="id" name="id" value="<?php echo encode($locationstatistic->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
