<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate("boat_pagetitle_list");
	$this->headTitle($title);
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("b.name", "c.owner"));
	$paginate->setFilterColumns(array("b.regno","b.id"));
	$paginate->setDefaultSortBy("b.name");	

	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT b.id, b.`name` AS `Name`, b.`regno` AS `Registration Number`, b.description AS `Description`, b.`owner` AS `Owner`, b.`type` AS `Type`, b.landingsiteid AS `Landing Site` FROM boat AS b WHERE b.name <> '' ".$paginate->getSearchAndFilterSQL()." GROUP BY b.id ".$paginate->getSortSQL();
	
	#debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 1;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";
?>

<form action="<?php echo $this->baseUrl("boat/listsearch"); ?>" method="get" id="usersform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
	      	 <tr>
	            <td><?php
					      	$typelist = new LookupType(); 
					      	$typelist->setName("BOAT_TYPES");
					       	$typedropdown = new Zend_Form_Element_Select('t'.HTML_TABLE_COLUMN_SEPARATOR.'type',
												array(
													'multiOptions' => array_merge_maintain_keys(array('' => 'Boat Types'), $typelist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
													'decorators' => array('ViewHelper'),
													'class' => array('filterselect', 'chzn-select')
												)
											);
							$typedropdown->setValue($request->getParam('t'.HTML_TABLE_COLUMN_SEPARATOR.'type')); 
							echo $typedropdown->render(); 
					      ?>
	              &nbsp;&nbsp;</td>
	            
	            <td><?php
					      	$landingsitelist = new LookupType(); 
					      	$landingsitelist->setName("ALL_LANDING_SITES");
					       	$landingsitedropdown = new Zend_Form_Element_Select('ls'.HTML_TABLE_COLUMN_SEPARATOR.'landingsiteid',
												array(
													'multiOptions' => array_merge_maintain_keys(array('' => 'All Landing Sites'), $landingsitelist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
													'decorators' => array('ViewHelper'),
													'class' => array('filterselect', 'chzn-select')
												)
											);
							$landingsitedropdown->setValue($request->getParam('ls'.HTML_TABLE_COLUMN_SEPARATOR.'landingsiteid')); 
							echo $landingsitedropdown->render(); 
					      ?></td>
	          </tr>
          </table>
      </td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="Enter your search term here and click search" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="Click here to Search or Filter"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="Search"/>Search</button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
  <?php } ?>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="error"><?php echo $this->translate("boat_list_norecords"); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("boat_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>  
  <?php if ($acl->checkPermission('Boat', ACTION_EXPORT)) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <div id="listresults_div">
    <h2><?php echo $title; ?></h2>
    <table class="list">
      <thead>
        <tr>
          <?php if ($acl->checkPermission('Boat', ACTION_EDIT)) {?>
          <td style="width:5%;">Edit</td>
          <?php } ?>
          <td><?php echo $paginate->getSortLinkForColumn('b.`name`','Name'); ?></td>
          <td><?php echo $paginate->getSortLinkForColumn('b.`owner`','Owner'); ?></td>
          <td><?php echo $paginate->getSortLinkForColumn('b.`regno`','Registration Number'); ?></td>
          <td><?php echo $paginate->getSortLinkForColumn('b.`type`','Type'); ?></td>
          <td><?php echo $paginate->getSortLinkForColumn('b.landingsiteid','Landing Site'); ?></td>
        </tr>
      </thead>
      <tbody>
        <?php 				  		
            	foreach($result as $line){							
            ?>
       <tr>
          <?php if ($acl->checkPermission('Boat', ACTION_EDIT)) {?>
          <td class="nowrapping"><a href="<?php echo $this->baseUrl("boat/index/id/".encode($line['id'])); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>"/></a></td>
          <?php } ?>
          <td class="nowrapping"><a href="<?php echo $this->baseUrl("boat/view/id/".encode($line['id'])); ?>"><?php echo $line['Name']; ?></a></td>
          <td><?php echo $line['Owner']; ?></td>
          <td><?php echo $line['Registration Number']; ?></td>
          <td><?php echo $line['Type']; ?></td>
          <td><?php echo $line['Landing Site']; ?></td>
        </tr>
        <?php 						
            	} // end processing results 
            ?>
      </tbody>
        </tr>
      
    </table>
  </div>
  <?php			
	} // end check that there are results    	
?><div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
