<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate("handcraft_pagetitle_list");
	$this->headTitle($title);
	
	if (isApplicationLGMIS()) {
		$request->setParam('c'.HTML_TABLE_COLUMN_SEPARATOR.'locationid', $session->getVar('districtid')); 
	}
	#generate the start and end dates
	$quarter_dates = getDatesForQuarter($request->quarter);
	$request->setParam('h__startdate', changeDateFromPageToMySQLFormat($quarter_dates['startdate']));		
	$request->setParam('h__enddate', changeDateFromPageToMySQLFormat($quarter_dates['enddate']));
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("l.name"));
	$paginate->setDefaultSortBy("co.name");	
	$paginate->setFilterColumns(array("l.locationid", "h.startdate", "h.enddate"));
	
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT h.id, l.name AS `Location`, co.name AS `Commodity`, h.retail AS `Retail`, h.wholesale AS `Whole Sale` FROM handcraftproduction AS h LEFT JOIN location l ON (h.locationid = l.id) LEFT JOIN commodity co ON (h.commodityid = co.id) ".$paginate->getSearchAndFilterSQL()." ".$paginate->getSortSQL();
	
	 //debugMessage($all_results_query);
	// exit();
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 1;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";	
?>

<form action="<?php echo $this->baseUrl("handcraftsectorlistsearch"); ?>" method="get" id="cropsectorform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <?php if (!isApplicationLGMIS()) { ?>
            <td><?php
					      	$districtlist = new LookupType(); 
					      	$districtlist->setName("ALL_DISTRICTS");
					       	$districtdropdown = new Zend_Form_Element_Select('c'.HTML_TABLE_COLUMN_SEPARATOR.'locationid',
												array(
													'multiOptions' => array_merge_maintain_keys(array('' => 'All Districts'), $districtlist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
													'decorators' => array('ViewHelper'),
													'class' => array('filterselect', 'chzn-select')
												)
											);
							$districtdropdown->setValue($request->getParam('c'.HTML_TABLE_COLUMN_SEPARATOR.'locationid')); 
							echo $districtdropdown->render(); 
					      ?></td>
            <?php } ?>
            <td><b><?php echo $this->translate("handcraft_quarter_label"); ?>:</b>
              <?php
            
            $quarterdropdown = new Zend_Form_Element_Select('quarter',
                                array(
                                    'multiOptions' => getYearQuartersList(),								
                                    'view' => new Zend_View(),
                                    'decorators' => array('ViewHelper'),
                                    'class' => array("filterselect", 'chzn-select'),
                                )
                            );
            $quarterdropdown->setValue($request->getParam('quarter')); 
            echo $quarterdropdown->render(); 
          ?></td>
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="Enter your search term here and click search" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="Click here to Search or Filter"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="Search"/>Search</button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
  <?php } ?>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="error"><?php echo $this->translate("handcraft_list_norecords"); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("handcraft_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>
  <?php if ($acl->checkPermission('Handcraft Sector Information', ACTION_EXPORT)) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <div id="listresults_div">
    <h2><?php echo $title; ?></h2>
    <table class="list">
      <thead>
        <tr>
          <td align="left" style="width:200px;"><?php echo $this->translate("handcraft_commodity_label"); ?></td>
          <td align="right"><?php echo $this->translate("handcraft_retail_label"); ?></td>
          <td align="right"><?php echo $this->translate("handcraft_wholesale_label"); ?></td>
        </tr>
      </thead>
      <tbody>
        <?php 				  		
            	foreach($result as $line){							
            ?>
        <tr>
          <td class="nowrapping"><b><?php echo $line['Commodity']; ?></b></td>
          <td align="right"><?php echo $line['Retail']; ?></td>
          <td align="right"><?php echo $line['Whole Sale']; ?></td>
        </tr>
        <?php 						
            	} // end processing results 
            ?>
      </tbody>
      <?php if ($acl->checkPermission('Handcraft Sector Information', ACTION_EDIT)) { ?>
      <tr>
        <td align="center" colspan="3"><a href="<?php echo $this->baseUrl("handcraftsector/index/quarter/".$request->quarter); ?>" class="positiveaction" title="<?php echo $this->translate("handcraft_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("handcraft_button_edit"); ?></a></td>
      </tr>
      <?php } ?>
    </table>
  </div>
  <?php			
	} // end check that there are results    	
?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
